name: "Hello world workflow"

on:
  push:
    branches:
      - main
      - test

jobs:
  hello_word:
    runs-on: ubuntu-latest
    steps:
      - name: "print hello world"
        run: echo "Hello world"
      
      - name: "Print current Date"
        run: date

      - name: "print whoami"
        run: whoami

      - name: "print pwd"
        run: pwd

      - name: "print ls"
        run: ls -la
